const Strings = {
  auth: {
    loginTitle: 'Log in to your account',
    loginSubtitle: 'Stay on top of your work, anywhere.',
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    forgotPassword: 'Forgot Password?',
    login: 'Log in',
    continueWithGoogle: 'Continue with Google',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
  },

  splash: {
    title: 'WorkPilot',
    subtitle: 'by Atlassian',
    loading: 'Loading...',
  },

  signUp: {
    headerTitle: 'Create your account',
    headerSubtitle: 'Join millions of teams on Jira',
    title: 'Create your account',
    subtitle: 'Join millions of teams using Jira.',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Your full name',
    workEmailLabel: 'Work Email',
    workEmailPlaceholder: 'you@company.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    userNameLabel: 'Username',
    userNamePlaceholder: 'Enter user name',
    passwordRules: {
      minLength: 'At least 8 characters',
      uppercase: 'One uppercase letter',
      number: 'One number',
      specialCharacter: 'One special character',
    },
    termsPrefix: 'By continuing to our',
    customerAgreement: 'Terms',
    termsMiddle: 'and',
    privacyPolicy: 'Privacy Policy',
    signUpButton: 'Sign up free',
    footerTitle: 'Already have an account?',
    footerAction: 'Log in',
  },

  forgotPassword: {
    headerTitle: 'Forgot Password',
    headerSubtitle: 'Reset your password',
    title: 'Forgot Password',
    subtitle:
      "Enter the mail address liked to your Attlassian account and we'll send you a reset link.",
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    sendOtpButton: 'Send OTP',
    footerTitle: 'Remember your password?',
    footerAction: 'Back to Log in',
    resetTitle: 'Check your email',
    resetSubtitle: "We've sent a password reset link to",
    resetFooterLabel: "Didn't receive it?",
    resetFooterAction: 'Resend email',
  },

  resetPassword: {
    headerTitle: 'Reset Password',
    subtitle: 'Create a new password',
    description:
      'Your new password must be different from your previous password.',
    validationLabel: "Passwords don't match",
    newPasswordLabel: 'New password',
    newPasswordPlaceholder: 'Enter your new password',
    confirmPasswordLabel: 'Confirm new password',
    confirmPasswordPlaceholder: 'Confirm your password',
    resetButton: 'Reset password',
    successTitle: 'Password reset!',
    successSubtitle:
      'Your password has been successfully reset. You can now log in with your new password.',
    backButton: 'Back to login',
  },

  verifyEmail: {
    headerTitle: 'Verify Email',
    headerSubtitle: 'Almost there',
    title: 'Verify your email',
    subtitle: "We've sent a 6-digit verification code to",
    otpLabel: 'Verification Code',
    verifyButton: 'Verify',
    resend: 'Resend Code',
    resendIn: 'Resend in',
    footerTitle: 'Wrong email?',
    footerAction: 'Go Back',
  },

  settings: {
    headerTitle: 'Settings',
    manageAccount: 'Manage account →',
    sections: {
      account: 'Account',
      profileVisibility: 'Profile & visibility',
      securityPrivacy: 'Security & privacy',
      languageRegion: 'Language & region',
      preferences: 'Preferences',
      notifications: 'Notifications',
      appearance: 'Appearance',
      theme: 'Theme',
      support: 'Support',
      helpCenter: 'Help center',
      aboutJira: 'About Jira',
    },
    atlassianSites: 'Atlassian sites',
    versionInfo: 'Jira Cloud · Version 10.14.2',
    copyright: '© 2026 Atlassian. All rights reserved.',
    logout: 'Log out',
  },

  theme: {
    dark: 'Dark',
    light: 'Light',
  },

  profile: {
    title: 'Profile',
    role: 'Senior Software Engineer',
    teamsTitle: 'Projects',
    recentActivity: 'Recent Activity',
    viewAll: 'View all',
    logout: 'Log out',
    assigned: 'Assigned',
    completed: 'Completed',
    in_progress: 'In Progress',
    completion_percentage: 'Completion %',
    starredIssues: 'Starred issues',
    myOpenIssues: 'My open issues',
    settings: 'Settings',
    favorites: 'Favorites',
    icons: {
      settings: 'settings-outline',
      edit: 'create-outline',
      starred: 'star-outline',
      openIssues: 'checkbox-outline',
      chevronRight: 'chevron-forward',
      logout: 'log-out-outline',
    },
  },
  common: {
    viewAll: 'View all',
  },
  home: {
    title: 'Home',
    greeting: 'Good morning,',
    userName: 'Alex Johnson',
    searchPlaceholder: 'Search issues, projects...',
    recentProjects: 'Recent Projects',
    myWork: 'My Work',
    starred: 'Starred',
    icons: {
      add: 'add',
      notifications: 'notifications-outline',
      search: 'search-outline',
      time: 'time-outline',
      star: 'star',
      chevronRight: 'chevron-forward',
    },
  },
  projectDetails: {
    defaultTitle: 'Project',
    softwareType: 'Software project',
    sprintInfo: 'Sprint 14 · 6 days left',
    boardTab: 'Board',
    backlogTab: 'Backlog',
    toDo: 'TO DO',
    inProgress: 'IN PROGRESS',
    inReview: 'IN REVIEW',
    done: 'DONE',
    addIssue: 'Add issue',
    testing: 'Testing',
    blocked: 'Blocked',
  },

  projectCard: {
    issues: 'issues',
  },
  backlog: {
    title: 'Backlog',
  },
  sprintSection: {
    backlogTitle: 'Backlog',
    activeBadge: 'ACTIVE',
    issuesLabel: 'issues',
    addIssueToBacklog: 'Add issue to backlog',
    addIssueToSprint: 'Add issue to sprint',
  },
  createIssue: {
    title: 'Create story',
    createButton: 'Create',
    projectLabel: 'Project',
    issueTypeLabel: 'Issue type',
    summaryLabel: 'Summary',
    summaryPlaceholder: 'What needs to be done?',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Add a description...',
    priorityLabel: 'Priority',
    assigneeLabel: 'Assignee',
    storyPointsLabel: 'Story points',
    addAttachment: 'Add attachment',
  },
  notification: {
    headerTitle: 'Notifications',
    actionMarkAllRead: '✓ All read',
    tabAll: 'All',
    tabUnread: 'Unread',
    emptyTitle: "You're all caught up!",
    emptySubtitle: 'No unread notifications right now.',
  },
  search: {
    placeholder: 'Search issues, projects, people...',
    recentSearches: 'Recent searches',
    trendingTitle: 'Trending in your workspace',
    resultSingle: 'result',
    resultPlural: 'results',
    for: 'for',
    noResultsTitle: 'No results found',
    noResultsSubtitle: 'Try searching with a different keyword.',
  },
  tabs: {
    home: 'Home',
    projects: 'Projects',
    search: 'Search',
    inbox: 'Inbox',
    you: 'You',
  },
  projects: {
    title: 'Projects',
    allProjects: 'All Projects',
    starred: 'Starred',
    searchPlaceholder: 'Search projects...',
    noResultsTitle: 'No projects found',
    noResultsSubtitle: 'Try searching for a different name or code.',
  },
  updateUser: {
    headerTitle: 'Update Profile Details',
    headerSubtitle:
      'Modify your profile information and account preferences below.',
    NameLabel: 'Full Name',
    userNameLabel: 'Username',
    emailLabel: 'Email Address',
    passwordLabel: 'Passwords',
    NamePlaceholder: 'Enter your full name',
    userNamePlaceholder: 'Enter your username',
    emailPlaceholder: 'Enter your email address',
    timezonePlaceholder: 'e.g. Asia/Calcutta',
    NameRequired: 'Full name is required',
    NameMinLength: 'Full name must be at least 3 characters',
    userNameRequired: 'Username is required',
    userNameInvalid: 'Username must be 3-20 characters (letters, numbers, _)',
    emailRequired: 'Email address is required',
    emailInvalid: 'Please enter a valid email address',
    timezoneRequired: 'Timezone is required',
    roleLabel: 'ROLE',
    statusLabel: 'STATUS',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    submitButton: 'Save Changes',
    successToastTitle: 'Success',
    successToastMessage: 'Profile details updated successfully!',
    errorToastTitle: 'Update Failed',
    defaultErrorMessage: 'Failed to update user details. Please try again.',
    imagePickerToast: 'Image picker opened',
  },
};

export default Strings;

export type StringsType = typeof Strings;
